image:
  repository: 526295688578.dkr.ecr.eu-west-1.amazonaws.com/lesson-8-9-ecr
  tag: "2"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

config:
  POSTGRES_HOST: ""
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "dbadmin"
  POSTGRES_DB: "mydatabase"
  ALLOWED_HOSTS: "*"

secret:
  POSTGRES_PASSWORD: ""