apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-config
data:
  POSTGRES_DB: {{ .Values.config.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ .Values.config.POSTGRES_USER | quote }}
  POSTGRES_HOST: {{ .Release.Name }}-postgres
  POSTGRES_PORT: {{ .Values.config.POSTGRES_PORT | quote }}